//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SketchTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG_FILES
    {
        public int ID { get; set; }
        public string IMG_FILEDATA { get; set; }
        public int DISPLAY_SATUS { get; set; }

        public virtual ANIMALS ANIMALS { get; set; }
        public virtual PARTS_OF_THE_BODY PARTS_OF_THE_BODY { get; set; }
        public virtual PEOPLE PEOPLE { get; set; }
        public virtual THINGS THINGS { get; set; }
    }
}
