//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SketchTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTS_OF_THE_BODY
    {
        public int PR_ID { get; set; }
        public string SECTION { get; set; }
        public int NUMBER { get; set; }
        public string POINT_V { get; set; }
        public string CONFIG { get; set; }
    
        public virtual CONFIGURATION CONFIGURATION { get; set; }
        public virtual IMG_FILES IMG_FILES { get; set; }
        public virtual POINTS_OF_VIEW POINTS_OF_VIEW { get; set; }
    }
}
