//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SketchTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTS_OF_VIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POINTS_OF_VIEW()
        {
            this.ANIMALS = new HashSet<ANIMALS>();
            this.PARTS_OF_THE_BODY = new HashSet<PARTS_OF_THE_BODY>();
            this.PEOPLE = new HashSet<PEOPLE>();
            this.THINGS = new HashSet<THINGS>();
        }
    
        public string V_KEY { get; set; }
        public string V_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANIMALS> ANIMALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTS_OF_THE_BODY> PARTS_OF_THE_BODY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEOPLE> PEOPLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THINGS> THINGS { get; set; }
    }
}
